// <auto-generated />
using HamburgerProject.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HamburgerProject.DATA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230126012044_NullablePropertyChangedAgain")]
    partial class NullablePropertyChangedAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExtraMaterialOrder", b =>
                {
                    b.Property<int>("EkstraMaterialsId")
                        .HasColumnType("int");

                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.HasKey("EkstraMaterialsId", "OrdersId");

                    b.HasIndex("OrdersId");

                    b.ToTable("ExtraMaterialOrder");
                });

            modelBuilder.Entity("HamburgerProject.DATA.ExtraMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ExtraMaterials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaterialName = "Ketçap",
                            Price = 5.0
                        },
                        new
                        {
                            Id = 2,
                            MaterialName = "Mayonez",
                            Price = 5.0
                        },
                        new
                        {
                            Id = 3,
                            MaterialName = "BBQ",
                            Price = 3.5
                        },
                        new
                        {
                            Id = 5,
                            MaterialName = "Ranch",
                            Price = 4.0
                        },
                        new
                        {
                            Id = 6,
                            MaterialName = "Buffalo",
                            Price = 5.5
                        });
                });

            modelBuilder.Entity("HamburgerProject.DATA.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuName = "Burger King Menüsü",
                            Price = 80.719999999999999
                        },
                        new
                        {
                            Id = 2,
                            MenuName = "Double King Chicken Menu",
                            Price = 100.72
                        },
                        new
                        {
                            Id = 3,
                            MenuName = "Steak House Menu",
                            Price = 98.719999999999999
                        },
                        new
                        {
                            Id = 4,
                            MenuName = "Whooper Menu",
                            Price = 78.719999999999999
                        },
                        new
                        {
                            Id = 5,
                            MenuName = "Whooper Jr. Menu",
                            Price = 128.72
                        },
                        new
                        {
                            Id = 6,
                            MenuName = "Chicken Royal Menu",
                            Price = 138.72
                        });
                });

            modelBuilder.Entity("HamburgerProject.DATA.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ExtraMaterialOrder", b =>
                {
                    b.HasOne("HamburgerProject.DATA.ExtraMaterial", null)
                        .WithMany()
                        .HasForeignKey("EkstraMaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamburgerProject.DATA.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HamburgerProject.DATA.Order", b =>
                {
                    b.HasOne("HamburgerProject.DATA.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });
#pragma warning restore 612, 618
        }
    }
}
